### ISSUE TITLE
Ubuntu install completed successfully, but doesn't work

### ISSUE THREAD

**Issue by jonahx** [Kerryliu/Native-Linux-on-Dell-Chromebook-13#1]
Hi,

I followed the instructions in the wiki and everything went well.  Ubuntu installed successfully and asked me to restart at the end.  I restarted, and a Ubuntu screen returned after restart instructing me to remove the USB media, and restart again.  I did that, but upon the final restart it just returned me to the chrome screen which says "OS Verification is OFF - Press Space to re-enable".  I did _not_ press space.  After 30 seconds it transitions to the "Chrome OS is missing or damaged" screen.

So, Ubuntu is installed, but is somehow inaccessible or not set correctly to boot.  Any ideas how I can fix this?

Thanks

**Comment by Kerryliu** [comment]
Iirc, you need to press ctrl+l to go past the chromeos screen and boot into
Linux.

**Comment by jonahx** [comment]
Worked.  Thanks for the quick answer, and thanks for posting this guide!

I don't suppose you know how to make it default boot into ubuntu every time without having to press ctrl-L?

**Comment by Kerryliu** [comment]
You'll have to open up the chromebook and remove the write protect screw in
order to boot linux by default. My internet is pretty awful right now so I
can't check, but there should be a link somewhere in the guide that tells
you how to do it.

**Comment by jonahx** [comment]
After successfully using ubuntu a couple times using the ctrl-L method to startup, it's not stopped working.  Pressing ctrl-L just makes a beep.  So somehow it seems to have lost the ability to boot into ubuntu.  Is there anything I can do at this point, or do I need to recover using chrome and then start the whole process over?  Any idea what could have caused it to get into this state?  Thanks again.

**Comment by Kerryliu** [comment]
I don't think that's ever happened to me before.  Do you have an SD card
inserted?

**Comment by jonahx** [comment]
No, nothing inserted.

**Comment by Kerryliu** [comment]
Hmm... only other thing I can think of is that the Chromebook might reset the boot flags if your battery runs dry.  I'm not sure if there's a way to fix that without restoring Chromeos, but you could try asking here: https://plus.google.com/communities/112479827373921524726

**Comment by jonahx** [comment]
Thanks for the link
